# Generated by Django 2.2.11 on 2020-03-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitnumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.CharField(max_length=200)),
                ('kitNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.Kitnumber')),
            ],
        ),
        migrations.CreateModel(
            name='NahibuClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('kitNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.Kitnumber')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('kitNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.Kitnumber')),
            ],
        ),
    ]
