# Generated by Django 2.2.11 on 2020-03-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nahibuclient',
            name='kitNumber',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='results',
            name='kitNumber',
            field=models.ForeignKey(on_delete=None, to='analyse.NahibuClient'),
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Kitnumber',
        ),
    ]
