# Generated by Django 2.2.11 on 2020-03-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0002_auto_20200321_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nahibuclient',
            name='kitNumber',
            field=models.CharField(max_length=300),
        ),
    ]
