# Generated by Django 2.2.11 on 2020-03-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_auto_20200321_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='kitNumber',
            field=models.ForeignKey(on_delete='CASCADE', to='analyse.NahibuClient'),
        ),
    ]
