# Generated by Django 2.2.11 on 2020-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0004_auto_20200321_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nahibuclient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='results',
            name='id',
        ),
        migrations.AlterField(
            model_name='nahibuclient',
            name='kitNumber',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='results',
            name='kitNumber',
            field=models.ForeignKey(on_delete='CASCADE', primary_key=True, serialize=False, to='analyse.NahibuClient'),
        ),
    ]
