# Generated by Django 2.2.11 on 2020-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0006_auto_20200321_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='results',
            name='kitNumber',
            field=models.OneToOneField(on_delete='CASCADE', to='analyse.NahibuClient'),
        ),
    ]
