# Generated by Django 2.2.11 on 2020-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0011_nahibuclient_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitNumber', models.CharField(max_length=300)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='nahibuclient',
            name='results',
            field=models.CharField(default='nolink', max_length=200),
        ),
    ]
